// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/slowhigh/goclean/infra/config"
	"github.com/slowhigh/goclean/infra/database"
	"github.com/slowhigh/goclean/infra/database/repository"
	"github.com/slowhigh/goclean/infra/router"
	"github.com/slowhigh/goclean/internal/controller/rest"
	"github.com/slowhigh/goclean/internal/usecase/memo"
)

// Injectors from wire.go:

func InitServer() (router.Router, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return router.Router{}, err
	}
	databaseDatabase, err := database.NewDatabase(configConfig)
	if err != nil {
		return router.Router{}, err
	}
	memoRepo := repository.NewMemo(databaseDatabase)
	memoUsecase := memo.NewMemoUsecase(memoRepo)
	memoController := rest.NewMemoController(memoUsecase)
	routerRouter := router.NewRouter(configConfig, memoController)
	return routerRouter, nil
}
